### ISSUE TITLE
Enabling debugger crashes game

### ISSUE THREAD

**Issue by Jordy1212** [BlastHackNet/mod_s0beit_sa#21] opened 2017-03-01 21:31 UTC
Main Menu -> Misc -> Debug -> Enable crashes my game. I think this bug was introduced in 4.4.1.0.

**Comment by pryon** [comment] 2017-06-28 18:36
This crash was caused by the `memcpy_safe()` function while copying data into the debug window for rendering in `RenderDebug()`.
It raised an access violation exception by trying to read bytes that it wasn't supposed to and not handling it in any way.
For some reason, somebody in the 4.4.1.0 patch decided to comment out the original, working memory safeguards inside `memcpy_safe()` and replaced them with plain `memcpy()` calls, entirely defeating the purpose of the `memcpy_safe()` function.

The PR restores the old, working memory checks and adds a few more last-function tracers to the rendering module for easier debugging.

**Comment by THE-FYP** [comment] 2017-07-06 09:19
Closed via #24.

**Closed by THE-FYP** 2017-07-06 09:19 UTC
